#pragma once
// Autogenerated by tools/extraction/emit_authentic_shapes.py
// Reference sample rate: 48000 Hz
// UPDATED: Added SUB pair from submodule (2025-11-03)

static const int AUTHENTIC_EMU_SAMPLE_RATE_REF = 48000;
static const int AUTHENTIC_EMU_NUM_SHAPES = 8;
static const int AUTHENTIC_EMU_NUM_PAIRS = 4;

static const float AUTHENTIC_EMU_SHAPES[8][12] = {
	{ 0.95f, 0.0104719755f, 0.96f, 0.0196349541f, 0.985f, 0.0392699082f, 0.992f, 0.117809725f, 0.993f, 0.327249235f, 0.985f, 0.458148929f }, //   0 A:vowel_pair
	{ 0.996f, 0.143989663f, 0.995f, 0.183259572f, 0.994f, 0.287979327f, 0.993f, 0.392699082f, 0.992f, 0.549778714f, 0.99f, 0.785398164f }, //   1 A:bell_pair
	{ 0.88f, 0.00392699082f, 0.9f, 0.00785398164f, 0.92f, 0.0157079633f, 0.94f, 0.0327249235f, 0.96f, 0.065449847f, 0.97f, 0.130899694f }, //   2 A:low_pair
	{ 0.85f, 0.00130899694f, 0.87f, 0.00261799388f, 0.89f, 0.00523598776f, 0.91f, 0.01047197551f, 0.93f, 0.02094395103f, 0.95f, 0.04188790206f }, //   3 A:sub_pair
	{ 0.96f, 0.00785398164f, 0.98f, 0.0314159261f, 0.985f, 0.044505896f, 0.992f, 0.130899694f, 0.99f, 0.287979327f, 0.985f, 0.392699082f }, //   4 B:vowel_pair
	{ 0.997f, 0.523598776f, 0.996f, 0.628318531f, 0.995f, 0.706858347f, 0.993f, 0.942477796f, 0.991f, 1.09955743f, 0.989f, 1.25663706f }, //   5 B:bell_pair
	{ 0.97f, 0.0261799388f, 0.985f, 0.065449847f, 0.99f, 0.157079633f, 0.992f, 0.235619449f, 0.99f, 0.366519143f, 0.988f, 0.471238898f }, //   6 B:low_pair
	{ 0.92f, 0.00872664626f, 0.94f, 0.01745329252f, 0.96f, 0.03490658504f, 0.97f, 0.06981317008f, 0.98f, 0.10471975511f, 0.97f, 0.13962634016f }, //   7 B:sub_pair
};

static const int MORPH_PAIRS[4][2] = {
	{ 0, 4 }, // vowel_pair
	{ 1, 5 }, // bell_pair
	{ 2, 6 }, // low_pair
	{ 3, 7 }, // sub_pair
};

static const char* AUTHENTIC_EMU_IDS[4] = {
	"vowel_pair",
	"bell_pair",
	"low_pair",
	"sub_pair",
};
